general.import = [
  # uncomment the flavour you want below:
  #"~/.config/alacritty/catppuccin-latte.toml"
   "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

# Font config:
[font]
    size = 11.0

    [font.bold]
        family = "FiraCode Nerd Font"
        style  = "Bold"

    [font.bold_italic]
        family = "FiraCode Nerd Font"
        style  = "Bold Italic"

    [font.glyph_offset]
        x = 0
        y = 0

    [font.italic]
        family = "FiraCode Nerd Font"
        style  = "Italic"

    [font.normal]
        family = "FiraCode Nerd Font"
        style  = "Regular"

    [font.offset]
        x = 0
        y = 0

[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]
